FROM python:3.9-slim

WORKDIR /app

# On ajoute explicitement les dépendances pour FastAPI et le multipart
RUN pip install --no-cache-dir \
    mlflow \
    scikit-learn \
    pandas \
    numpy \
    psycopg2-binary \
    fastapi \
    uvicorn \
    python-multipart \
    jinja2

COPY . /app

EXPOSE 5002

# Commande de lancement (sera écrasée par le docker-compose si spécifié là-bas)
CMD ["uvicorn", "Trainmodel:app", "--host", "0.0.0.0", "--port", "5002"]